# Generated by Django 5.1.2 on 2024-11-04 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_order',
            name='status',
        ),
    ]
