# Generated by Django 5.1.2 on 2024-11-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='price',
            field=models.FloatField(),
        ),
    ]
