# Generated by Django 5.1.2 on 2024-11-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_remove_purchase_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='price',
            field=models.FloatField(blank=True, default=2.25),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='total_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
