# Generated by Django 5.1.2 on 2024-11-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_alter_purchaseorder_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
