# Generated by Django 5.1.2 on 2024-11-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0003_alter_purchase_order_price_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='purchase_order',
            new_name='PurchaseOrder',
        ),
    ]
