# Generated by Django 5.1.2 on 2024-12-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('image', models.URLField(blank=True, null=True)),
                ('frequency', models.IntegerField(blank=True, default=0, null=True)),
                ('printed_papers', models.IntegerField(blank=True, default=0, null=True)),
                ('allowed_types', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
