# Generated by Django 5.1.2 on 2024-11-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0002_printer_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='printed_papers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
