# Generated by Django 5.1.2 on 2024-11-30 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0002_alter_printer_image'),
        ('printer', '0003_printer_printed_papers'),
    ]

    operations = [
    ]
