# Generated by Django 5.1.2 on 2024-11-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='images',
            field=models.TextField(blank=True),
        ),
    ]
