# Generated by Django 5.1.2 on 2024-11-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='money_spent',
            field=models.FloatField(default=0),
        ),
    ]
