# Generated by Django 5.1.2 on 2024-11-01 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lastSignedIn',
            new_name='last_signed_in',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='student_id',
            new_name='user_id',
        ),
    ]
