# Generated by Django 5.1.2 on 2024-11-16 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('printer', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='print_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=125, null=True)),
                ('file_to_be_printed', models.FileField(upload_to='files/')),
                ('status', models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('pending', 'pending')], max_length=7)),
                ('orientation', models.CharField(choices=[('portrait', 'portrait'), ('landscape', 'landscape')], default='portrait', max_length=10)),
                ('sided', models.CharField(choices=[('single', 'single'), ('double', 'double')], default='single', max_length=6)),
                ('page_side', models.CharField(choices=[('A3', 'A3'), ('A4', 'A4')], default='A4', max_length=2)),
                ('copies', models.IntegerField(default=1)),
                ('timer_start', models.DateTimeField(auto_now_add=True)),
                ('timer_end', models.DateTimeField(blank=True, null=True)),
                ('page_cost', models.IntegerField(blank=True, default=0)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printer.printer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
