# Generated by Django 5.1.2 on 2024-11-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print_order',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('pending', 'pending')], max_length=7),
        ),
        migrations.AlterField(
            model_name='print_order',
            name='timer_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
