# Generated by Django 5.1.2 on 2024-11-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0002_alter_print_order_status_alter_print_order_timer_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='print_order',
            name='file_name',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='print_order',
            name='page_cost',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
