# Generated by Django 5.1.2 on 2024-11-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='user',
            new_name='student_id',
        ),
    ]
